# Generated by Django 5.1.4 on 2024-12-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_product_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
