# Generated by Django 5.1.4 on 2024-12-29 12:25

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_customeruser_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(max_length=9, null=True, unique=True, validators=[shop.models.validate_phone_numer]),
        ),
    ]
